#
# FileName:     {{_file_name_}}
# Author: 		{{_author_}}
# CreatedDate:  {{_date_}}
# LastModified: 2023-02-03 21:27:40 +0900
# Reference: 	https://qiita.com/chibi929/items/b8c5f36434d5d3fbfa4a
# Description:	---
#




.PHONY: run clean debug


run:
	{{_cursor_}}

debug:


clean:
	rm 

