snippet _8:temp template
    #
    # FileName:     Dockerfile
    # Author:       8ucchiman
    # CreatedDate:  {{_date_}}
    # LastModified: 2023-01-26 17:46:51 +0900
    # Reference:    8ucchiman.jp
    # Description:  ---
    #

